//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvcBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Send
    {
        public int EmailId { get; set; }
        public string Kim { get; set; }
        public string Kime { get; set; }
        public string Konu { get; set; }
        public string Mesaj { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> UlkeId { get; set; }
    
        public virtual TelKodu TelKodu { get; set; }
    }
}
