//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvcBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelKodu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelKodu()
        {
            this.Send = new HashSet<Send>();
        }
    
        public int Id { get; set; }
        public string UlkeKodu { get; set; }
        public string UlkeAd { get; set; }
        public string UlkeBayrak { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Send> Send { get; set; }
    }
}
